apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven:latest
      command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      imagePullPolicy: Always # use cache or pull image for agent
    - name: docker
      image: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
